name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  # Firebase dependencies
  firebase_core: ^3.12.0  
  firebase_auth: ^5.5.0  
  cloud_firestore: ^5.6.4  
  firebase_database: ^11.3.3 
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^17.0.0
  intl: ^0.18.0
  lucide_icons: ^0.257.0
  # Other dependencies
  provider: ^6.1.2  # ✅ Fixed version issue
  flutter_spinkit: ^5.1.0  
  cupertino_icons: ^1.0.6  
  lottie: ^3.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Fertilizer.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/agriculture_ad.jpg  # ✅ Ensure these files exist in the assets folder
    - assets/agriculture1.jpg
    - assets/agriculture3.jpg
    - assets/agriculture4.jpg
    - assets/a5.jpg
    - assets/a6.jpg
    - assets/a7.jpg
    - assets/a8.jpg
    - assets/loading.json
    - assets/Fertilizer.jpg
    