// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwlqRSOtKz__WAmCihYlr9UEy_PDneAo',
    appId: '1:615436559823:web:2f5013ec68de79a062deba',
    messagingSenderId: '615436559823',
    projectId: 'fertilizer-5841a',
    authDomain: 'fertilizer-5841a.firebaseapp.com',
    storageBucket: 'fertilizer-5841a.firebasestorage.app',
    measurementId: 'G-C5W2GDCHBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-LVRDhCmBk5r9abFQUhefvU0Poj4WRs',
    appId: '1:615436559823:android:988dbfa4d0d2748e62deba',
    databaseURL: "https://fertilizer-5841a-default-rtdb.firebaseio.com/",
    messagingSenderId: '615436559823',
    authDomain: "fertilizer-5841a.firebaseapp.com",
    projectId: 'fertilizer-5841a',
    storageBucket: 'fertilizer-5841a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFkFiNtW3Zg2k_Ufr89Z4p0uTkHc-Twc',
    appId: '1:615436559823:ios:84810f7ea9e5656d62deba',
    messagingSenderId: '615436559823',
    projectId: 'fertilizer-5841a',
    storageBucket: 'fertilizer-5841a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFkFiNtW3Zg2k_Ufr89Z4p0uTkHc-Twc',
    appId: '1:615436559823:ios:84810f7ea9e5656d62deba',
    messagingSenderId: '615436559823',
    projectId: 'fertilizer-5841a',
    storageBucket: 'fertilizer-5841a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwlqRSOtKz__WAmCihYlr9UEy_PDneAo',
    appId: '1:615436559823:web:df8c9297fc8a76b462deba',
    messagingSenderId: '615436559823',
    projectId: 'fertilizer-5841a',
    authDomain: 'fertilizer-5841a.firebaseapp.com',
    storageBucket: 'fertilizer-5841a.firebasestorage.app',
    measurementId: 'G-0BP10Q12SV',
  );
}
